
set(Slicer_CMAKE_DIR "/home/nathan/Documents/Slicer/CMake")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(CTEST_MODEL "Experimental")
set(Slicer_WC_REVISION "ab21644")
set(EXTENSION_NAME "FastSlice")
set(EXTENSION_CATEGORY "Examples")
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/WandEffect.png")
set(EXTENSION_CONTRIBUTORS "John Doe (AnyWare Corp.)")
set(EXTENSION_DESCRIPTION "This is an example of a simple extension")
set(EXTENSION_HOMEPAGE "http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/WandEffect2")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/WandEffect/Screenshots/1.png")
set(EXTENSION_ENABLED "1")
set(EXTENSION_OPERATING_SYSTEM "linux")
set(EXTENSION_ARCHITECTURE "amd64")
set(EXTENSION_WC_TYPE "git")
set(EXTENSION_WC_URL "https://github.com/FastSlice/WandEffect")
set(EXTENSION_WC_REVISION "2aa9a78")
set(EXTENSION_BINARY_DIR "/home/nathan/Documents/WandEffect-build/.")